import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { HelpCircle } from 'lucide-react';

export function Tooltip({ children, content, position = 'top' }) {
  const [isVisible, setIsVisible] = useState(false);

  const positionClasses = {
    top: 'bottom-full left-1/2 -translate-x-1/2 mb-2',
    bottom: 'top-full left-1/2 -translate-x-1/2 mt-2',
    left: 'right-full top-1/2 -translate-y-1/2 mr-2',
    right: 'left-full top-1/2 -translate-y-1/2 ml-2',
  };

  const arrowClasses = {
    top: 'top-full left-1/2 -translate-x-1/2 border-t-gray-800 border-x-transparent border-b-transparent',
    bottom: 'bottom-full left-1/2 -translate-x-1/2 border-b-gray-800 border-x-transparent border-t-transparent',
    left: 'left-full top-1/2 -translate-y-1/2 border-l-gray-800 border-y-transparent border-r-transparent',
    right: 'right-full top-1/2 -translate-y-1/2 border-r-gray-800 border-y-transparent border-l-transparent',
  };

  return (
    <div
      className="relative inline-flex"
      onMouseEnter={() => setIsVisible(true)}
      onMouseLeave={() => setIsVisible(false)}
    >
      {children}
      <AnimatePresence>
        {isVisible && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ duration: 0.15 }}
            className={`absolute z-50 ${positionClasses[position]}`}
          >
            <div className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 max-w-xs shadow-xl">
              {content}
            </div>
            <div className={`absolute w-0 h-0 border-4 ${arrowClasses[position]}`} />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export function InfoTooltip({ content, position = 'top' }) {
  return (
    <Tooltip content={content} position={position}>
      <HelpCircle className="w-4 h-4 text-gray-500 hover:text-gray-300 cursor-help transition-colors" />
    </Tooltip>
  );
}

// Energy metric explanations
export const METRIC_EXPLANATIONS = {
  // Solar
  solarPower: "Current power being generated by your solar panels in kilowatts (kW). This varies based on sunlight intensity.",
  solarToday: "Total energy generated by solar panels today in kilowatt-hours (kWh). Resets at midnight.",
  solarTotal: "Lifetime total energy generated by your solar system since installation.",
  solarArrayVoltage: "The DC voltage output from this solar array. Higher voltage typically means better sunlight conditions.",
  solarArrayCurrent: "The electrical current flowing from this array in Amps. Varies with sunlight intensity.",
  solarArrayPower: "Power output from this specific array. Calculated as Voltage × Current.",
  peakPower: "The highest power output recorded today. Useful for understanding your system's maximum capacity.",

  // Battery
  batteryPercent: "Current state of charge (SOC) of your battery. 100% means fully charged, 0% means empty.",
  batteryPower: "Current power flow to/from battery. Positive = charging, Negative = discharging.",
  batteryTemperature: "Battery operating temperature. Optimal range is typically 15-35°C. High temps can reduce lifespan.",
  batteryCapacity: "Total energy storage capacity of your battery system in kilowatt-hours (kWh).",
  batteryVoltage: "Nominal operating voltage of the battery pack.",
  depthOfDischarge: "Maximum percentage of battery capacity that can be used. Protects battery longevity.",
  batteryCharge: "Energy added to the battery today through charging.",
  batteryDischarge: "Energy drawn from the battery today for home use or grid export.",
  batteryCycles: "Number of complete charge/discharge cycles today. One cycle = 100% capacity throughput.",
  timeRemaining: "Estimated time until battery depletes at current discharge rate.",

  // Grid
  gridPower: "Current power exchange with the grid. Positive = importing (buying), Negative = exporting (selling).",
  gridVoltage: "Mains voltage from the grid. UK standard is ~230V. Variations are normal.",
  gridFrequency: "AC frequency of the grid. UK standard is 50Hz. Slight variations indicate grid load.",
  gridCurrent: "Electrical current flowing to/from the grid in Amps.",
  powerFactor: "Ratio of real power to apparent power (0-1). Closer to 1 means more efficient power use.",
  gridImport: "Total energy imported (bought) from the grid today.",
  gridExport: "Total energy exported (sold) to the grid today.",
  netGridPosition: "Difference between export and import. Positive = net exporter, Negative = net importer.",

  // Consumption
  consumptionPower: "Current power being used by your home in kilowatts (kW).",
  consumptionToday: "Total energy consumed by your home today in kilowatt-hours (kWh).",
  selfPowered: "Percentage of consumption met by solar + battery vs grid. Higher = more energy independent.",
  selfSufficiency: "How much of your energy needs are met by your own generation.",

  // Device
  inverterSerial: "Unique identifier for your GivEnergy inverter.",
  dongleSerial: "Serial number of the communication device (WiFi/GPRS dongle).",
  firmwareARM: "Version of the ARM processor firmware. Controls system logic.",
  firmwareDSP: "Version of the DSP firmware. Controls power conversion.",
  maxChargeRate: "Maximum power at which the battery can be charged.",
  maxDischargeRate: "Maximum power at which the battery can discharge.",
  warrantyExpiry: "Date when your equipment warranty expires.",

  // EMS
  emsStatus: "Energy Management System status. NORMAL means operating correctly.",
  errorCode: "System error code. 0 or empty means no errors.",
  warningCode: "System warning code. Non-critical issues that may need attention.",
  calculatedLoad: "Home consumption calculated by the system based on energy flows.",
  measuredLoad: "Home consumption directly measured by CT clamp or meter.",

  // General
  lastUpdated: "When data was last received from your inverter. Updates every 5-10 seconds typically.",
  refreshRate: "Dashboard fetches new data every 30 seconds automatically.",
};
