'use client';
import { useState } from 'react';
import { Info } from 'lucide-react';

export const METRIC_EXPLANATIONS = {
  // Solar
  solarPower: "Current power being generated by your solar panels in kilowatts (kW).",
  solarToday: "Total energy generated by solar panels today in kilowatt-hours (kWh).",
  solarTotal: "Lifetime total energy generated by your solar system.",
  solarArray: "Individual solar panel string. Multiple arrays can face different directions.",
  arrayVoltage: "Voltage output from this solar array. Higher voltage typically means more sunlight.",
  arrayCurrent: "Current (amps) flowing from this solar array.",

  // Battery
  batteryPercent: "Current battery charge level as a percentage of total capacity.",
  batteryPower: "Power flowing to/from battery. Positive = charging, Negative = discharging.",
  batteryTemp: "Battery temperature. Optimal range is 15-25°C for lithium batteries.",
  batteryCharge: "Total energy charged into the battery today.",
  batteryDischarge: "Total energy discharged from the battery today.",

  // Grid
  gridPower: "Power flowing to/from grid. Positive = importing, Negative = exporting.",
  gridVoltage: "Mains voltage from the grid. UK standard is ~230V.",
  gridFrequency: "Grid frequency. UK standard is 50Hz.",
  gridImport: "Total energy imported from grid today.",
  gridExport: "Total energy exported to grid today.",

  // Consumption
  consumptionPower: "Current power being used by your home in kilowatts.",
  consumptionToday: "Total energy consumed by your home today.",

  // Inverter
  inverterTemp: "Inverter operating temperature. Should stay below 60°C.",
  inverterPower: "Power being processed by the inverter.",
  outputVoltage: "AC voltage output from the inverter to your home.",
  outputFrequency: "AC frequency output from the inverter.",

  // EV Charger
  evStatus: "Current status of EV charger (Available, Charging, etc.).",
  evPower: "Power being delivered to the electric vehicle.",
  evEnergy: "Total energy delivered in current charging session.",
};

export function InfoTooltip({ metricKey, className = '' }) {
  const [isVisible, setIsVisible] = useState(false);
  const explanation = METRIC_EXPLANATIONS[metricKey];

  if (!explanation) return null;

  return (
    <div className={`relative inline-block ${className}`}>
      <button
        onMouseEnter={() => setIsVisible(true)}
        onMouseLeave={() => setIsVisible(false)}
        onFocus={() => setIsVisible(true)}
        onBlur={() => setIsVisible(false)}
        className="p-1 rounded-full hover:bg-white/10 transition-colors"
        aria-label="More information"
      >
        <Info className="w-4 h-4 text-gray-500 hover:text-gray-300" />
      </button>

      {isVisible && (
        <div className="absolute z-50 bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 p-3 bg-gray-800 border border-gray-700 rounded-lg shadow-xl">
          <p className="text-sm text-gray-300 leading-relaxed">{explanation}</p>
          <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-1">
            <div className="border-8 border-transparent border-t-gray-800" />
          </div>
        </div>
      )}
    </div>
  );
}

export function Tooltip({ children, content }) {
  const [isVisible, setIsVisible] = useState(false);

  return (
    <div className="relative inline-block">
      <div
        onMouseEnter={() => setIsVisible(true)}
        onMouseLeave={() => setIsVisible(false)}
      >
        {children}
      </div>

      {isVisible && content && (
        <div className="absolute z-50 bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 p-3 bg-gray-800 border border-gray-700 rounded-lg shadow-xl">
          <p className="text-sm text-gray-300 leading-relaxed">{content}</p>
          <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-1">
            <div className="border-8 border-transparent border-t-gray-800" />
          </div>
        </div>
      )}
    </div>
  );
}
